name: Stripe Automation

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-stripe-script:
    runs-on: windows-latest
    steps:
      # 1) Check out your code
      - uses: actions/checkout@v3

      # 2) Run your PowerShell script
      - name: Run Stripe Script
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        run: pwsh scripts/charge-cycles.ps1
