name: Stripe Automation

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/15 * * * *'   # runs every 15 minutes
  workflow_dispatch:

jobs:
  run-stripe-script:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PowerShell
        uses: actions/setup-powershell@v3

      - name: Run Stripe Script
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        run: pwsh scripts/charge-cycles.ps1
